### ISSUE TITLE
Eyes on code (2nd opinion)

### ISSUE THREAD

**Issue by lakruzz** [Churnr/churnr#48]
Hej @KingBendico Gider du lige løbe den her igennem? 🙏 

[Mit seneste commit](https://github.com/Churnr/churnr/commit/8b8d00561f639cf8049c2100a9c30c2d54011c8e)

https://github.com/Churnr/churnr/commit/8b8d00561f639cf8049c2100a9c30c2d54011c8e

**Comment by KingBendico** [comment]
Ok
